name: Generate Trophy
on:
  schedule:
    - cron: "0 0 * * *"   # daily refresh
  workflow_dispatch:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ryo-ma/github-profile-trophy@master
        with:
          username: ranatalhamajid1
          output_path: profile-trophy.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          theme: algolia
          no-frame: true
          no-bg: true
          margin-w: 8
      - name: Commit trophy
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add profile-trophy.svg
          git commit -m "Update trophy" || echo "No changes"
          git push
